Factory/FactoryWeb/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FactoryWeb.Funcionalidades.ListarEmpresa;
using FactoryWeb.Funcionalidades.RegistrarEmpresa;

namespace FactoryWeb.Controllers
{
    [Authorize]
    public class EmpresaController : Controller
    {
        // GET: Empresa
        public ActionResult Lista()
        {
            using (var listarFactura = new ListarEmpresaHandler())
            {
                return View(listarFactura.Ejecutar());
            }
        }

        [HttpGet]
        public ActionResult Registrar()
        {
            return View(new RegistrarEmpresaViewModel());
        }

        [HttpPost]
        public ActionResult Registrar(RegistrarEmpresaViewModel modelo)
        {
            if (!ModelState.IsValid) return View(modelo);

            using (var registrarEmpresa = new RegistrarEmpresaHandler())
            {
                try
                {
                    registrarEmpresa.Ejecutar(modelo);
                    return RedirectToAction("Lista");

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }

            }
        }

    }
}

Factory/FactoryWeb/Controllers/FacturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FactoryWeb.Funcionalidades.ListarFactura;
using FactoryWeb.Funcionalidades.RegistrarFactura;

namespace FactoryWeb.Controllers
{
    [Authorize]
    public class FacturaController : Controller
    {
        // GET: Factura
        public ActionResult Lista()
        {
            using (var listarFactura = new ListarFacturaHandler())
            {
                return View(listarFactura.Ejecutar());
            }
        }

        [HttpGet]
        public ActionResult Registrar()
        {
            return View(new RegistrarFacturaViewModel());
        }


        [HttpPost]
        public ActionResult Registrar(RegistrarFacturaViewModel modelo)
        {
            if (!ModelState.IsValid) return View(modelo);

            using (var registrarFactura = new RegistrarFacturaHandler())
            {
                try
                {
                    registrarFactura.Ejecutar(modelo);
                    return RedirectToAction("Lista");

                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(modelo);
                }

            }
        }



    }
}

Factory/FactoryWeb/Views/Empresa/Lista.cshtml
@model IEnumerable<FactoryWeb.Funcionalidades.ListarEmpresa.ListarEmpresaViewModel>

@{
    ViewBag.Title = "Lista de Empresas";
}

<h2>Lista de Empresas</h2>

<p>
   @* @Html.ActionLink("Create New", "Create")*@
    @Html.ActionLink("Create New", "Registrar", "Empresa"
                   //, new { rol = @Model.us }
                   //, new AjaxOptions
                   //{
                   //    HttpMethod = "Get",
                   //    InsertionMode = InsertionMode.Replace,
                   //    UpdateTargetId = "RegistrarRolControlAccion"
                   //}
                   //,
                   //new
                   //{
                   //    data_toggle = "modal",
                   //    data_target = "#RegistrarRolControlAccion"
                   //}
                   )
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RUC)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RazonSocial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Departamento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Provincia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Distrito)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rubro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdUsuario)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RUC)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RazonSocial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Direccion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Departamento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Provincia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Distrito)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rubro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdUsuario)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })|
            @Html.ActionLink("Registrar Factura", "Registrar", "Factura")|
            @Html.ActionLink("Ver Facturas","Lista","Factura")|
        </td>
    </tr>
}

</table>

Factory/FactoryWeb/Views/Empresa/Registrar.cshtml
@model FactoryWeb.Funcionalidades.RegistrarEmpresa.RegistrarEmpresaViewModel

@{
    ViewBag.Title = "Registrar";
}

<h2>Registrar Empresas</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RegistrarEmpresaViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RUC, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RUC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RUC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RazonSocial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RazonSocial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RazonSocial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Departamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Departamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Departamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Provincia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Provincia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Provincia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Distrito, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Distrito, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Distrito, "", new { @class = "text-danger" })
            </div>
        </div>*@

                @*inicio-------------*@

                <div id="empresa-ubigeo">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Departamento, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5">
                            @Html.HiddenFor(model => model.Departamento, new { @id = "departamento_nombre", @class = "departamento" })
                            @Html.DropDownList("departamento", Model.Departamentos,
                                new { @id = "persona_departamento", @class = "form-control departamento" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Provincia, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5">
                            @Html.HiddenFor(model => model.Provincia, new { @id = "provincia_nombre", @class = "provincia" })
                            @Html.DropDownList("provincia", Model.Provincias,
                                new { @id = "persona_provincia", @class = "form-control provincia" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Distrito, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5">
                            @Html.HiddenFor(model => model.Distrito, new { @id = "distrito_nombre", @class = "distrito" })
                            @Html.DropDownList("distrito", Model.Distritos,
                                new { @id = "persona_distrito", @class = "form-control distrito" })
                        </div>
                    </div>
                </div>

                @*fin--------------------*@

        <div class="form-group">
            @Html.LabelFor(model => model.Rubro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rubro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rubro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdUsuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdUsuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/registrarempresa")@*/jg*@
}